version: '2'
services:
    docker:
        build: ./test_env/docker/
        privileged: true
        restart: always
        volumes:
            - ~/.kube/:/.kube/
            - d54-data:/demo-tests/d54
            - organon-data:/demo-tests/organon
        environment:
            # This disables TLS for the dind image HOTFIX
            DOCKER_TLS_CERTDIR: ""

    tests:
        build: .
        environment:
            DOCKER_HOST: tcp://docker:2375
            DOCKER_HOST_URL: docker
            ASPERATHOS_URL: docker:1500/submissions
            VISUALIZER_URL: docker:5002/visualizing
        volumes:
            - .:/integration-tests/.
            - d54-data:/demo-tests/d54
            - organon-data:/demo-tests/organon
        depends_on:
            - docker

volumes:
    d54-data:
        external: true
    organon-data:
        external: true
